# Generated by Django 6.0.5 on 2026-05-06 12:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('usd_exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.0'), help_text='Applied as a multiplier during price normalization. Default is 1.0.', max_digits=12)),
                ('enabled', models.BooleanField(default=True)),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetch_status', models.CharField(choices=[('never', 'Never'), ('success', 'Success'), ('failed', 'Failed')], default='never', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'base_url'],
            },
        ),
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_url', models.URLField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_excerpt', models.TextField(blank=True)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_runs', to='collector.competitorsite')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('quota_type', models.PositiveSmallIntegerField(choices=[(0, 'Token'), (1, 'Request')])),
                ('input_price_usd_per_1m', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('output_price_usd_per_1m', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('request_price_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('raw_model_ratio', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('raw_completion_ratio', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('raw_model_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('raw_cache_ratio', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('raw_create_cache_ratio', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('billing_mode', models.CharField(blank=True, max_length=64)),
                ('billing_expr', models.TextField(blank=True)),
                ('raw_enable_groups_json', models.TextField(blank=True)),
                ('snapshot_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fetch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='collector.fetchrun')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='collector.competitorsite')),
            ],
            options={
                'ordering': ['model_name', 'site__name', 'site__base_url'],
                'indexes': [models.Index(fields=['model_name'], name='collector_m_model_n_c3523c_idx'), models.Index(fields=['site', 'model_name'], name='collector_m_site_id_e98c0c_idx'), models.Index(fields=['fetch_run'], name='collector_m_fetch_r_5e0df6_idx')],
            },
        ),
    ]
