# Generated by Django 6.0.5 on 2026-05-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_revert_clear_model_name_segment_reorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpricesnapshot',
            options={'ordering': ['-snapshot_at', 'normalized_model_name']},
        ),
        migrations.RemoveIndex(
            model_name='modelpricesnapshot',
            name='collector_m_clear_m_73af39_idx',
        ),
        migrations.RemoveIndex(
            model_name='modelpricesnapshot',
            name='collector_m_site_id_e67cbb_idx',
        ),
        migrations.RenameField(
            model_name='modelpricesnapshot',
            old_name='clear_model_name',
            new_name='normalized_model_name',
        ),
        migrations.AddIndex(
            model_name='modelpricesnapshot',
            index=models.Index(fields=['normalized_model_name'], name='collector_m_normali_95fba8_idx'),
        ),
        migrations.AddIndex(
            model_name='modelpricesnapshot',
            index=models.Index(fields=['site', 'normalized_model_name'], name='collector_m_site_id_37453b_idx'),
        ),
    ]
