# Generated by Django 6.0.5 on 2026-05-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_userplansubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
