# Generated by Django 6.0.5 on 2026-05-08 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_logincode_attempt_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(default='epay', max_length=32)),
                ('payment_method', models.CharField(blank=True, max_length=32)),
                ('plan_code', models.CharField(max_length=32)),
                ('billing_cycle', models.CharField(max_length=32)),
                ('amount_rmb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('provider_payload_json', models.TextField(blank=True, default='{}')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argus_payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
