# Generated by Django 6.0.5 on 2026-05-08 06:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_paymentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model_name', models.CharField(max_length=255, unique=True)),
                ('target_model_name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_model_name'],
            },
        ),
        migrations.CreateModel(
            name='NormalizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_usd_exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('7.20'), max_digits=12)),
                ('ranking_mode', models.CharField(choices=[('input_output', 'Input and output'), ('input_only', 'Input only'), ('output_only', 'Output only'), ('display_only', 'Display only')], default='input_output', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Normalization settings',
            },
        ),
    ]
