# Generated by Django 6.0.5 on 2026-05-08 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_modelalias_normalizationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsite',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='argus_competitor_sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitorsite',
            name='base_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='competitorsite',
            constraint=models.UniqueConstraint(fields=('owner', 'base_url'), name='collector_site_owner_base_url_unique'),
        ),
    ]
