# Generated by Django 6.0.5 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_competitorsite_owner_alter_competitorsite_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsite',
            name='system_start_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitorsite',
            name='system_version',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]