# Generated by Django 6.0.5 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_competitorsite_status_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
